import asyncio
import os
import re
import json
import requests
from typing import Union

import yt_dlp
from pyrogram.enums import MessageEntityType
from pyrogram.types import Message
from youtubesearchpython.__future__ import VideosSearch

from maythusharmusic.utils.database import is_on_off
from maythusharmusic.utils.formatters import time_to_seconds

# --- Cookies Configuration Start ---
COOKIES_DICT = {
    'PREF': 'tz=Asia.Rangoon&f5=30000&f7=100',
    'GPS': '1',
    'YSC': 'F3EHjUCULgA',
    'VISITOR_INFO1_LIVE': 'OIUABJ7IxXY',
    'VISITOR_PRIVACY_METADATA': 'CgJNTRIEGgAgKQ%3D%3D',
    '__Secure-ROLLOUT_TOKEN': 'CIm62KKTyfD7hgEQ6azU8dnvkgMYp-PJldrvkgM%3D',
    '__Secure-1PSIDTS': 'sidts-CjUBBj1CYk42j_3roA7VulNa9CCXXR_QY1J_eC-kub3YGvKsYGo44YIgpt48ukT2WsVOwzwwLBAA',
    '__Secure-3PSIDTS': 'sidts-CjUBBj1CYk42j_3roA7VulNa9CCXXR_QY1J_eC-kub3YGvKsYGo44YIgpt48ukT2WsVOwzwwLBAA',
    'HSID': 'AxOxPyyCqDXCwQGFl',
    'SSID': 'AWtNocNTfN7V-EJoP',
    'APISID': 'ft3V-HjuunR-tBKY/A-8t9oIyMczufNIQw',
    'SAPISID': 'yheS2GsD8pFQAwQi/AdV_Fy_dqfOGkKGl8',
    '__Secure-1PAPISID': 'yheS2GsD8pFQAwQi/AdV_Fy_dqfOGkKGl8',
    '__Secure-3PAPISID': 'yheS2GsD8pFQAwQi/AdV_Fy_dqfOGkKGl8',
    'SID': 'g.a0007AiljrA5Ep0YIqgbJOhlygeY1sL94S_f9D_iZfX0mLe3iOnTP6WdFJ7KlA0JcGVa-Z2f5gACgYKAaISARcSFQHGX2Misw2EhWRNxzanln6E1mYqPBoVAUF8yKrNEPSV_0lvUPBQmZSDfVpj0076',
    '__Secure-1PSID': 'g.a0007AiljrA5Ep0YIqgbJOhlygeY1sL94S_f9D_iZfX0mLe3iOnTNNSMIRDC8WgoMPr_ERBFxQACgYKARoSARcSFQHGX2MiSgrryy9XqpyCsfeLsSzEKxoVAUF8yKp7vzMkh5QHP-pBImw9X_fe0076',
    '__Secure-3PSID': 'g.a0007AiljrA5Ep0YIqgbJOhlygeY1sL94S_f9D_iZfX0mLe3iOnT1sg7L2NZCEpNYQK0H3sf-gACgYKAdYSARcSFQHGX2Mi7BtA_6EjvzM1LbKPSAThDRoVAUF8yKogZx7-6mLZbXqL56ZbRUl_0076',
    'LOGIN_INFO': 'AFmmF2swRQIgYlIGyk4KdR1rKxUbPMp0z6IZ1G9WWjWuT7Bq1MxDJpkCIQCegzG9X5odniKBe3MHf5OPQobm0FprHJZq6NlQZc9rgA:QUQ3MjNmeUk0ell5UFhxVG9OaHVSM2Z2X1plRHpzTWhSeG43SnZIOXhvZURYMlZXbkg2M251OEpWUTdvREctdUZjdlUxbHJDMFRXSTJGYTNrcEF0dkpXWGVpTmJfRUJRamtfSGdhZzhNOXdpR1U0WGpQZXM2bVR5RHdNN0VIMlZmbzEwaE1hd3hTbUhUYUFqZzdDQWIxV29OWmJCMHFMb1F3',
    'SIDCC': 'AKEyXzU99mDj976wDSXLeX3b0O1fcmGod900IIC_cQj4vHnWjsITCMrCmUvp9z2WfVimgCcn',
    '__Secure-1PSIDCC': 'AKEyXzUKdz5F-5K_DqoD8saEpDsxn89mUzPwmeF2GxvqqWSM-ZOhHP9vGhuu0U-JP323-E4tTg',
    '__Secure-3PSIDCC': 'AKEyXzUDG_HE1891naJl-XnXkA1qQuUuZ8i4EKYqlJh-ybfdl9n3xddHjWAJVVioYmExBb8IOg',
}

def create_cookies_file():
    """Converts the COOKIES_DICT to a Netscape format cookies.txt file"""
    content = "# Netscape HTTP Cookie File\n"
    content += "# This file is generated by maythusharmusic Bot\n\n"
    
    for key, value in COOKIES_DICT.items():
        content += f".youtube.com\tTRUE\t/\tTRUE\t2147483647\t{key}\t{value}\n"
        content += f".google.com\tTRUE\t/\tTRUE\t2147483647\t{key}\t{value}\n"
        
    with open("cookies.txt", "w") as f:
        f.write(content)

if not os.path.exists("cookies.txt"):
    create_cookies_file()
else:
    create_cookies_file()
# --- Cookies Configuration End ---


async def shell_cmd(cmd):
    proc = await asyncio.create_subprocess_shell(
        cmd,
        stdout=asyncio.subprocess.PIPE,
        stderr=asyncio.subprocess.PIPE,
    )
    out, errorz = await proc.communicate()
    if errorz:
        if "unavailable videos are hidden" in (errorz.decode("utf-8")).lower():
            return out.decode("utf-8")
        else:
            return errorz.decode("utf-8")
    return out.decode("utf-8")


class YouTubeAPI:
    def __init__(self):
        self.base = "https://www.youtube.com/watch?v="
        self.regex = r"(?:youtube\.com|youtu\.be)"
        self.status = "https://www.youtube.com/oembed?url="
        self.listbase = "https://youtube.com/playlist?list="
        self.reg = re.compile(r"\x1B(?:[@-Z\\-_]|\[[0-?]*[ -/]*[@-~])")
        self.cookie_path = "cookies.txt"

    async def exists(self, link: str, videoid: Union[bool, str] = None):
        if videoid:
            link = self.base + link
        if re.search(self.regex, link):
            return True
        else:
            return False

    async def url(self, message_1: Message) -> Union[str, None]:
        messages = [message_1]
        if message_1.reply_to_message:
            messages.append(message_1.reply_to_message)
        text = ""
        offset = None
        length = None
        for message in messages:
            if offset:
                break
            if message.entities:
                for entity in message.entities:
                    if entity.type == MessageEntityType.URL:
                        text = message.text or message.caption
                        offset, length = entity.offset, entity.length
                        break
            elif message.caption_entities:
                for entity in message.caption_entities:
                    if entity.type == MessageEntityType.TEXT_LINK:
                        return entity.url
        if offset in (None,):
            return None
        return text[offset : offset + length]

    async def suggestion(self, link: str):
        loop = asyncio.get_running_loop()
        def fetch_suggestions():
            try:
                url = "https://suggestqueries-clients6.youtube.com/complete/search"
                params = {
                    "client": "firefox",
                    "ds": "yt",
                    "q": link,
                    "hl": "en",
                    "gl": "US",
                }
                headers = {
                    "User-Agent": "Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/96.0.4664.110 Safari/537.36"
                }
                response = requests.get(url, params=params, headers=headers)
                data = response.json()
                if data and len(data) > 1:
                    return data[1]
                return []
            except Exception as e:
                return []
        return await loop.run_in_executor(None, fetch_suggestions)

    async def get_recommendations(self, videoid: str):
        try:
            mix_url = f"https://www.youtube.com/watch?v={videoid}&list=RD{videoid}"
            cmd = f"yt-dlp --cookies {self.cookie_path} --get-id --flat-playlist --playlist-end 5 --skip-download {mix_url}"
            result = await shell_cmd(cmd)
            video_ids = result.strip().split("\n")
            recommendations = [vid for vid in video_ids if vid != videoid and vid != ""]
            if recommendations:
                return recommendations[0]
            return None
        except Exception:
            return None

    async def details(self, link: str, videoid: Union[bool, str] = None):
        if videoid:
            link = self.base + link
        if "&" in link:
            link = link.split("&")[0]
        results = VideosSearch(link, limit=1)
        for result in (await results.next())["result"]:
            title = result["title"]
            duration_min = result["duration"]
            thumbnail = result["thumbnails"][0]["url"].split("?")[0]
            vidid = result["id"]
            if str(duration_min) == "None":
                duration_sec = 0
            else:
                duration_sec = int(time_to_seconds(duration_min))
        return title, duration_min, duration_sec, thumbnail, vidid

    async def title(self, link: str, videoid: Union[bool, str] = None):
        if videoid:
            link = self.base + link
        if "&" in link:
            link = link.split("&")[0]
        results = VideosSearch(link, limit=1)
        for result in (await results.next())["result"]:
            title = result["title"]
        return title

    async def duration(self, link: str, videoid: Union[bool, str] = None):
        if videoid:
            link = self.base + link
        if "&" in link:
            link = link.split("&")[0]
        results = VideosSearch(link, limit=1)
        for result in (await results.next())["result"]:
            duration = result["duration"]
        return duration

    async def thumbnail(self, link: str, videoid: Union[bool, str] = None):
        if videoid:
            link = self.base + link
        if "&" in link:
            link = link.split("&")[0]
        results = VideosSearch(link, limit=1)
        for result in (await results.next())["result"]:
            thumbnail = result["thumbnails"][0]["url"].split("?")[0]
        return thumbnail

    async def video(self, link: str, videoid: Union[bool, str] = None):
        if videoid:
            link = self.base + link
        if "&" in link:
            link = link.split("&")[0]
        # Direct link for streaming/playing
        cmd = f"yt-dlp --cookies {self.cookie_path} -g -f best[height<=?720][width<=?1280] {link}"
        proc = await asyncio.create_subprocess_shell(
            cmd,
            stdout=asyncio.subprocess.PIPE,
            stderr=asyncio.subprocess.PIPE,
        )
        stdout, stderr = await proc.communicate()
        if stdout:
            return 1, stdout.decode().split("\n")[0]
        else:
            return 0, stderr.decode()

    async def playlist(self, link, limit, user_id, videoid: Union[bool, str] = None):
        if videoid:
            link = self.listbase + link
        if "&" in link:
            link = link.split("&")[0]
        cmd = f"yt-dlp --cookies {self.cookie_path} -i --get-id --flat-playlist --playlist-end {limit} --skip-download {link}"
        playlist = await shell_cmd(cmd)
        try:
            result = playlist.split("\n")
            for key in result:
                if key == "":
                    result.remove(key)
        except:
            result = []
        return result

    async def track(self, link: str, videoid: Union[bool, str] = None):
        if videoid:
            link = self.base + link
        if "&" in link:
            link = link.split("&")[0]
        results = VideosSearch(link, limit=1)
        for result in (await results.next())["result"]:
            title = result["title"]
            duration_min = result["duration"]
            vidid = result["id"]
            yturl = result["link"]
            thumbnail = result["thumbnails"][0]["url"].split("?")[0]
        track_details = {
            "title": title,
            "link": yturl,
            "vidid": vidid,
            "duration_min": duration_min,
            "thumb": thumbnail,
        }
        return track_details, vidid

    async def formats(self, link: str, videoid: Union[bool, str] = None):
        if videoid:
            link = self.base + link
        if "&" in link:
            link = link.split("&")[0]
        ytdl_opts = {"quiet": True, "cookiefile": self.cookie_path}
        ydl = yt_dlp.YoutubeDL(ytdl_opts)
        with ydl:
            formats_available = []
            r = ydl.extract_info(link, download=False)
            for format in r["formats"]:
                try:
                    str(format["format"])
                except:
                    continue
                if not "dash" in str(format["format"]).lower():
                    try:
                        format["format"]
                        format["filesize"]
                        format["format_id"]
                        format["ext"]
                        format["format_note"]
                    except:
                        continue
                    formats_available.append(
                        {
                            "format": format["format"],
                            "filesize": format["filesize"],
                            "format_id": format["format_id"],
                            "ext": format["ext"],
                            "format_note": format["format_note"],
                            "yturl": link,
                        }
                    )
        return formats_available, link

    async def slider(
        self,
        link: str,
        query_type: int,
        videoid: Union[bool, str] = None,
    ):
        if videoid:
            link = self.base + link
        if "&" in link:
            link = link.split("&")[0]
        a = VideosSearch(link, limit=10)
        result = (await a.next()).get("result")
        title = result[query_type]["title"]
        duration_min = result[query_type]["duration"]
        vidid = result[query_type]["id"]
        thumbnail = result[query_type]["thumbnails"][0]["url"].split("?")[0]
        return title, duration_min, thumbnail, vidid

    async def download(
        self,
        link: str,
        mystic,
        video: Union[bool, str] = None,
        videoid: Union[bool, str] = None,
        songaudio: Union[bool, str] = None,
        songvideo: Union[bool, str] = None,
        format_id: Union[bool, str] = None,
        title: Union[bool, str] = None,
    ) -> str:
        if videoid:
            link = self.base + link
        loop = asyncio.get_running_loop()

        common_opts = {
            "geo_bypass": True,
            "nocheckcertificate": True,
            "quiet": True,
            "no_warnings": True,
            "cookiefile": self.cookie_path,
        }

        def audio_dl():
            opts = common_opts.copy()
            opts.update({
                "format": "bestaudio/[ext=m4a]",
                "outtmpl": "downloads/%(id)s.%(ext)s",
            })
            x = yt_dlp.YoutubeDL(opts)
            info = x.extract_info(link, False)
            xyz = os.path.join("downloads", f"{info['id']}.{info['ext']}")
            if os.path.exists(xyz):
                return xyz
            x.download([link])
            return xyz

        # --- Video Download Logic (Improved for MP4) ---
        def video_dl():
            opts = common_opts.copy()
            opts.update({
                # Select Best MP4 Video (Max 720p) + Best M4A Audio
                "format": "(bestvideo[height<=?720][width<=?1280][ext=mp4])+(bestaudio[ext=m4a])",
                "outtmpl": "downloads/%(id)s.%(ext)s",
                "merge_output_format": "mp4", # Ensure output is MP4
            })
            x = yt_dlp.YoutubeDL(opts)
            info = x.extract_info(link, False)
            xyz = os.path.join("downloads", f"{info['id']}.{info['ext']}")
            if os.path.exists(xyz):
                return xyz
            x.download([link])
            return xyz

        def song_video_dl():
            # Merges selected video format with best available audio
            formats = f"{format_id}+bestaudio" 
            fpath = f"downloads/{title}"
            opts = common_opts.copy()
            opts.update({
                "format": formats,
                "outtmpl": fpath,
                "prefer_ffmpeg": True,
                "merge_output_format": "mp4", # Forces final container to be MP4
            })
            x = yt_dlp.YoutubeDL(opts)
            x.download([link])
        # ---------------------------------------------

        def song_audio_dl():
            fpath = f"downloads/{title}.%(ext)s"
            opts = common_opts.copy()
            opts.update({
                "format": format_id,
                "outtmpl": fpath,
                "prefer_ffmpeg": True,
                "postprocessors": [
                    {
                        "key": "FFmpegExtractAudio",
                        "preferredcodec": "mp3",
                        "preferredquality": "192",
                    }
                ],
            })
            x = yt_dlp.YoutubeDL(opts)
            x.download([link])

        if songvideo:
            await loop.run_in_executor(None, song_video_dl)
            fpath = f"downloads/{title}.mp4"
            return fpath
        elif songaudio:
            await loop.run_in_executor(None, song_audio_dl)
            fpath = f"downloads/{title}.mp3"
            return fpath
        elif video:
            if await is_on_off(1):
                direct = True
                downloaded_file = await loop.run_in_executor(None, video_dl)
            else:
                # Direct Stream Link with Cookie
                cmd = f"yt-dlp --cookies {self.cookie_path} -g -f best[height<=?720][width<=?1280] {link}"
                proc = await asyncio.create_subprocess_shell(
                    cmd,
                    stdout=asyncio.subprocess.PIPE,
                    stderr=asyncio.subprocess.PIPE,
                )
                stdout, stderr = await proc.communicate()
                if stdout:
                    downloaded_file = stdout.decode().split("\n")[0]
                    direct = None
                else:
                    return
        else:
            direct = True
            downloaded_file = await loop.run_in_executor(None, audio_dl)
        return downloaded_file, direct
